### ISSUE TITLE
 ERROR: number of words should be greater than 0

### ISSUE THREAD

**Issue by liminglives** [Intel-bigdata/HiBench#36]
I use hibench as my benchmark tool. When I do bayes and nutchindexing test, this error comes to in the beginning:

14/04/14 13:05:15 INFO HiBench.NutchData: Initializing Nutch data generator...
curIndex: 2012, total: 2013
ERROR: number of words should be greater than 0

The Hibench version is 2.2, Hadoop is 1.2.1, jdk is 1.6.0.26, and ubuntu is 12.04

by the way, I checked my ubuntu, and it has /usr/share/dict/words, but not found /usr/share/dict/linux.words. I do not know if it matters.

**Comment by manishagajbe** [comment]
I am getting the similar error. 
curIndex: 334, total: 335
ERROR: number of words should be greater than 0

I do not have the default dict file "/usr/share/dict/linux.words", however I have "/usr/share/dict/american"

Is there a way I can change the default input file to prepare data for HiBench/nutchindexing?

JAVA_HOME=/opt/java/jdk1.7.0_45
Hibench version is 2.2
Hadoop is 2.1.0

**Comment by manishagajbe** [comment]
I have created a softlink for linux.words file. However, I still observe the same error message. The file is not empty.

curIndex: 334, total: 335
ERROR: number of words should be greater than 0
