### ISSUE TITLE
HiBench Installation Guide

### ISSUE THREAD

**Issue by dcheng1709** [Intel-bigdata/HiBench#43]
I download HiBench to my PC. I can't find any executable file to install HiBench. In addition,  my Hadoop exists on AWS. Do I have to install HiBench in AWS? Where I can find the HiBench Installation Guide / instruction.

Thanks.

David

**Comment by laminucsy** [comment]
I am a beginner who try to test Hibench in hadoop cluster and I don't know well about HIbench. Currently, my cluster does not support spark but I would like to run specific workload like kmeans, wordcount, and so on. I am now using HIbench 4.0.  I run workload hibench and the output shows the following errors 

"reduce.EventFetcher: EventFetcher is interrupted.. Returning"
"HiBench.HiveData$GenerateRankingsReducer: pid: 0, 0 erros, 0 missed" 

I don't know what to proceed. And I would like to know where is the input data folder and output folder for specific workload run. If it is possible, please explain to me about HIBench!    Thank you very much in advance!
