### ISSUE TITLE
Do not generate hibench.report after successfully testing

### ISSUE THREAD

**Issue by tobegit3hub** [Intel-bigdata/HiBench#577]
We have used HiBench for benchmark testing. In our environment we have successfully run the tests but the report file in `./report/hibench.report` did not generated.

<img width="1438" alt="Screenshot 2019-03-29 at 3 56 05 PM" src="https://user-images.githubusercontent.com/2715000/55217794-57237380-523b-11e9-8bec-1512e437b6a8.png">

The `./conf/hibench.conf` has not changed the report file path.

<img width="840" alt="Screenshot 2019-03-29 at 3 57 56 PM" src="https://user-images.githubusercontent.com/2715000/55217865-86d27b80-523b-11e9-840c-ca93e8dd795e.png">

**Comment by tobegit3hub** [comment]
It seems to be my problem when I did not install bc in that server.

It would be better if we can throw exceptions or log about this.

**Comment by CMDebugger** [comment]
> 
> 
> It seems to be my problem when I did not install bc in that server.
> 
> It would be better if we can throw exceptions or log about this.

I  gree with you. It would be nice if Hibench inform user with Warming or log about the issue.

**Comment by BowangFang** [comment]
I have met the same problem
