### ISSUE TITLE
K-Means data generation standard deviation is less than zero

### ISSUE THREAD

**Issue by PovelikinRostislav** [Intel-bigdata/HiBench#600]
autogen/src/main/java/org/apache/mahout/clustering/kmeans/GenKMeansDataset.java file has the following default configurations:
```
double stdMin = -100;
```

Standard deviation can't be less than 0 by definition. HIbench uses such deviations for Gaussian Generators with the following implementation from [uncommons.math](https://github.com/dwdyer/uncommons-maths/blob/b7ba13aea70625bb7f37c856783a29e17e354964/core/src/java/main/org/uncommons/maths/random/GaussianGenerator.java):
```
return rng.nextGaussian() * standardDeviation.nextValue() + mean.nextValue();
```
where `standardDeviation.nextValue()` will use passed negative number thus you can't see any error detection.

**Comment by xwu99** [comment]
@PovelikinRostislav 
I found stdMin is used there: 
ContinuousUniformGenerator ugStd = new ContinuousUniformGenerator(stdMin, stdMax, rng);

it's ContinuousUniformGenerator not GaussianGenerator, Could you double check?

**Comment by xwu99** [comment]
stdMin is used in UniformGenerator which produces -standardDeviation to standardDeviation.

`ContinuousUniformGenerator` ugStd = new ContinuousUniformGenerator(stdMin, stdMax, rng);

`rng.nextGaussian()` produce (0, 1) and scaled with ugStd, so the final result is produced around mean (smaller or larger).

**Comment by xwu99** [comment]
stdMin is used in UniformGenerator.
ContinuousUniformGenerator ugStd = new ContinuousUniformGenerator(stdMin, stdMax, rng);
Do you mean stdMin should be 0?

**Comment by PovelikinRostislav** [comment]
@xwu99, and values generated from this uniform generator are passed to Gaussian generator at line 234 with possibly negative values for standard deviation.

I mean that it should be literally any value more than 0

**Comment by xwu99** [comment]
@PovelikinRostislav, I understand your concerns. 
@carsonwang seems Rostislav is right. ugStd should produce a positive number (could be 0?). The original version seems to work as ugStd scale rng.nextGaussian() with -standardDeviation to standardDeviation, just flip around axis.
