### ISSUE TITLE
run_all.sh script error because of there isn't the hadoop directory  in micro repartition.

### ISSUE THREAD

**Issue by godtree** [Intel-bigdata/HiBench#613]
[root@cdh1 bin]# sh run_all.sh
......
Run micro/repartition/hadoop
Exec script: /opt/HiBench/bin/workloads/micro/repartition/hadoop/run.sh
run_all.sh: line 86: /opt/HiBench/bin/workloads/micro/repartition/hadoop/run.sh: No such file or directory
ERROR: micro/repartition/hadoop failed to run successfully.
[root@cdh1 bin]# ll /opt/HiBench/bin/workloads/micro/repartition/
total 8
drwxr-xr-x 2 root root 4096 Apr  7 15:55 prepare
drwxr-xr-x 2 root root 4096 Apr  7 15:55 spark

**Comment by carsonwang** [comment]
Thanks for catching this! The new repartition workload is only available for Spark. we should update run_all.sh. @gczsjdy

**Comment by gczsjdy** [comment]
Thanks @godtree @carsonwang Let me fix this.
