### ISSUE TITLE
Are there 25 workloads in HiBench 7.0 ?

### ISSUE THREAD

**Issue by godtree** [Intel-bigdata/HiBench#615]
https://github.com/Intel-bigdata/HiBench

The README.md says
"There are totally 19 workloads in HiBench."
But I count 25 workloads.
（micro 6 + ml 11 + sql 1 + websearch 2 + graph 1 + streaming 4）

**Comment by gczsjdy** [comment]
Actually it's 27. There are 3 SQL workloads, fixed in #616

**Comment by godtree** [comment]
Great, thanks.

**Comment by godtree** [comment]
@gczsjdy Great, thanks.
