### ISSUE TITLE
Hadoop 3 and Spark 3

### ISSUE THREAD

**Issue by hebabaze** [Intel-bigdata/HiBench#620]
Hello 
Hadoop 3 and Spark 3 are they supported or not yet ?!

**Comment by ConeyLiu** [comment]
@hebabaze , I am not working on this project anymore. `Spark 3.0` has not released yet, I think `HiBench` doesn't support it. Hi @gczsjdy, do you know about `Hadoop 3.X` has supported or not?

**Comment by gczsjdy** [comment]
@hebabaze See https://github.com/Intel-bigdata/HiBench/issues/614#issuecomment-615033342
