### ISSUE TITLE
Mahout's extra-download-execution step fails as a referenced URL is stuck behind authentication

### ISSUE THREAD

**Issue by JigsawCorp** [Intel-bigdata/HiBench#659]
Hi,

**Problem:** It appears that a file hosted on Cloudera is now behind authentication, which prevents building the Mahout module.

**Steps to reproduce:**

1. Download HiBench repo.
2. Attempt to build Hadoop framework: `mvn -Phadoopbench -Dspark=2.4 -Dscala=2.11 clean package`

This results in the following error message: `[WARNING] Could not get content
org.apache.maven.wagon.authorization.AuthorizationException: Authentication failed for http://archive.cloudera.com/cdh5/cdh/5/mahout-0.9-cdh5.1.0.tar.gz 401 Authentication required`

Is there any mirror where I could obtain this file? This prevents me from building HiBench.

**Comment by Pl4tiNuM** [comment]
Hello,

probably a duplicate of #657 

Regards

**Comment by JigsawCorp** [comment]
@Pl4tiNuM You are right, this is a duplicate of #657. Therefore I am closing this one.
